<x-app-layout>
    <div class="container ">
        <div class="row">
            <div class="col-12">
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
                <h1>ciao</h1>
            </div>
        </div>
    </div>
</x-app-layout>
